#  Media configurations
media:
  WebRTCHangupRetryInterval: 2000
  # IP address of FreeSWITCH server for use of mod_verto and WebRTC deshsharing
  vertoServerAddress: "HOST"
  # Allows a caller to access a FreeSWITCH dialplan
  freeswitchProfilePassword: "1234"  # TODO: Remove once Danny's submitted PULL
  vertoPort: "8082"
  # specifies whether to use SIP.js for audio over mod_verto
  useSIPAudio: true
